// Code generated by entc, DO NOT EDIT.

package car

const (
	// Label holds the string label denoting the car type in the database.
	Label = "car"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCarNo holds the string denoting the car_no field in the database.
	FieldCarNo = "car_no"

	// EdgePredicament holds the string denoting the predicament edge name in mutations.
	EdgePredicament = "predicament"

	// Table holds the table name of the car in the database.
	Table = "cars"
	// PredicamentTable is the table the holds the predicament relation/edge.
	PredicamentTable = "predicaments"
	// PredicamentInverseTable is the table name for the Predicament entity.
	// It exists in this package in order to avoid circular dependency with the "predicament" package.
	PredicamentInverseTable = "predicaments"
	// PredicamentColumn is the table column denoting the predicament relation/edge.
	PredicamentColumn = "carid"
)

// Columns holds all SQL columns for car fields.
var Columns = []string{
	FieldID,
	FieldCarNo,
}

var (
	// CarNoValidator is a validator for the "car_no" field. It is called by the builders before save.
	CarNoValidator func(string) error
)
