/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPredicament,
    EntPredicamentFromJSON,
    EntPredicamentFromJSONTyped,
    EntPredicamentToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * Predicament holds the value of the predicament edge.
     * @type {Array<EntPredicament>}
     * @memberof EntUserEdges
     */
    predicament?: Array<EntPredicament>;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'predicament': !exists(json, 'predicament') ? undefined : ((json['predicament'] as Array<any>).map(EntPredicamentFromJSON)),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'predicament': value.predicament === undefined ? undefined : ((value.predicament as Array<any>).map(EntPredicamentToJSON)),
    };
}


